task:
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $CIRRUS_OS
  matrix:
    - container:
        image: ubuntu:22.04
      install_script:
        - export RUNLEVEL=1
        - apt-get update
        - apt-get install -y apt-utils lsb-release curl 
        - apt-get update
        - apt-get install -y dialog python3 python3-pip git wget unzip ftp
        #- apt-get install -y dialog python3-pip build-essential doxygen graphviz
        #- apt-get install -y software-properties-common libreadline8 libreadline-dev
        #- apt-get install -y clang-10
        #- update-alternatives --install /usr/bin/clang clang /usr/bin/clang-10 100
        #- python3 -m pip install --upgrade --requirement requirements.txt


#  version_script:
#    - python3 --version
  script:
    # basic configuration
    #- python waf configure -v
    - python3 pjh.py
    ## documentation build
    #- python3 waf build_docs
    #- python3 waf clean_docs
    #- python3 waf distclean
    ## configuration
    #- python3 waf configure --include-tests
    ## gcc [
    #- python3 waf build_gcc -v
    #- python3 waf install_gcc -v
    #- pushd build/gcc/tests
    #- lua -e"_U=true" all.lua
    ##- lua all.lua
    #- popd
    #- python3 waf uninstall_gcc
    #- python3 waf clean_gcc
    ## gcc ]
    #- python3 waf distclean
    ## including ltests
    #- python3 waf configure --ltests --include-tests
    ## gcc [
    #- python3 waf build_gcc -v
    #- python3 waf install_gcc -v
    #- pushd build/gcc/tests
    #- lua -e"_U=true" all.lua
    ##- lua all.lua
    #- popd
    #- python3 waf uninstall_gcc
    #- python3 waf clean_gcc
    ## gcc ]
    ## configuration
    #- python3 waf configure --include-tests
    ## clang [
    #- python3 waf build_clang -v
    #- python3 waf install_clang -v
    #- pushd build/clang/tests
    #- lua -e"_U=true" all.lua
    ##- lua all.lua
    #- popd
    #- python3 waf uninstall_clang
    #- python3 waf clean_clang
    ## clang ]
    #- python3 waf distclean
    ## including ltests
    #- python3 waf configure --ltests --include-tests
    ## clang [
    #- python3 waf build_clang -v
    #- python3 waf install_clang -v
    #- pushd build/clang/tests
    #- lua -e"_U=true" all.lua
    ##- lua all.lua
    #- popd
    #- python3 waf uninstall_clang
    #- python3 waf clean_clang
    ## clang ]
    ## test script
    #- python3 scripts/run_test.py -c gcc -c clang --simple-test
    #- python3 scripts/run_test.py -c gcc -c clang --simple-test --ltests
